### PR TITLE
Add composer.json

### PR DESCRIPTION
**Pull request by mixcas**

### CODE REVIEW

**Comment by varffs** [comment]
Def needs autoload value

**Comment by mixcas** [comment]
@varffs no, CMB2 doesnt have it

**Comment by varffs** [comment]
https://github.com/fightbulc/moment.php/blob/master/composer.json

**Comment by mixcas** [comment]
@varffs do u realize the diff between how `moment` is written and CMB2 and this plugin?

https://github.com/WebDevStudios/CMB2/commit/e4d03897689a16d0231c2a344fc15b0439e2155f

**Comment by varffs** [comment]
Ah true better not as CMB2 doesnt

**Pull request merged**
